{{- if eq .Values.mode "cluster" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mast.edge.fullname" . }}
  labels:
    {{- include "mast.labels" . | nindent 4 }}
    app.kubernetes.io/component: edge
  {{- with .Values.edge.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.edge.service.type }}
  selector:
    {{- include "mast.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: edge
  ports:
    - name: mqtt
      port: {{ .Values.edge.service.mqttPort }}
      targetPort: mqtt
    {{- if gt (int .Values.edge.internalPort) 0 }}
    - name: mqtt-internal
      port: {{ .Values.edge.internalPort }}
      targetPort: mqtt-internal
    {{- end }}
    {{- if gt (int .Values.edge.wsPort) 0 }}
    - name: mqtt-ws
      port: {{ .Values.edge.wsPort }}
      targetPort: mqtt-ws
    {{- end }}
{{- end }}
